### ISSUE TITLE
using headless service to DNS ROS master cluster IP

### ISSUE THREAD

**Issue by fujitatomoya** [fujitatomoya/ros_k8s#6]
Here are the examples for ROS 1 deployment using headless service. the followings are just examples, probably not working correctly.

- master

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roscore-deployment
  labels:
    app: rosmaster
    node: roscore
spec:
  replicas: 1
  selector:
    matchLabels:
      node: roscore
  template:
    metadata:
      labels:
        node: roscore
    spec:
      containers:
      - name: rosmaster
        image: ros:noetic
        args:
        - roscore
        ports:
        - containerPort: 11311
          name: roscoreport
      nodeSelector:
        nodename: master

---

apiVersion: v1
kind: Service
metadata:
  name: ros-master
  labels:
    app: rosmaster
    node: roscore
spec:
  clusterIP: None
  ports:
    - port: 11311
  selector:
    node: roscore
```

- talker / listener

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talker-deployment
  labels:
    app: rostalker
    node: talker
spec:
  replicas: 1
  selector:
    matchLabels:
      node: talker
  template:
    metadata:
      labels:
        node: talker
    spec:
      containers:
      - name: rospublisher
        image: ros:noetic
        args:
        - "rostopic"
        - "pub"
        - "-r 1"
        - "chatter"
        - "std_msgs/String"
        - "Hello, world"
        env:
        - name: ROS_MASTER_URI
          value: http://ros-master:11311
        - name: ROS_HOSTNAME
          value: ros-talker
      nodeSelector:
        nodename: slave
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-deployment
  labels:
    app: roslistener
    node: listener
spec:
  replicas: 1
  selector:
    matchLabels:
      node: listener
  template:
    metadata:
      labels:
        node: listener
    spec:
      containers:
      - name: roslistener
        image: ros:noetic
        args:
        - rostopic
        - echo
        - chatter
        env:
        - name: ROS_MASTER_URI
          value: http://ros-master:11311
        - name: ROS_HOSTNAME
          value: ros-listener
      nodeSelector:
        nodename: master

---

# not sure this is required...
apiVersion: v1
kind: Service
metadata:
  name: ros-listener
  labels:
    app: roscluster
    node: listener
spec:
  clusterIP: None
  ports:
    - port: 11311
  selector:
    node: listener
```
